-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (Document(..), DocumentPage(..), User(..), UserPage(..))


type Document
    = Document


type DocumentPage
    = DocumentPage


type User
    = User


type UserPage
    = UserPage
