-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (Document(..), Document_aggregate(..), Document_aggregate_fields(..), Document_max_fields(..), Document_min_fields(..), Document_mutation_response(..), User(..), User_aggregate(..), User_aggregate_fields(..), User_max_fields(..), User_min_fields(..), User_mutation_response(..))


type Document
    = Document


type Document_aggregate
    = Document_aggregate


type Document_aggregate_fields
    = Document_aggregate_fields


type Document_max_fields
    = Document_max_fields


type Document_min_fields
    = Document_min_fields


type Document_mutation_response
    = Document_mutation_response


type User
    = User


type User_aggregate
    = User_aggregate


type User_aggregate_fields
    = User_aggregate_fields


type User_max_fields
    = User_max_fields


type User_min_fields
    = User_min_fields


type User_mutation_response
    = User_mutation_response
