-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.ScalarCodecs exposing (Id, Jsonb, codecs)

import Api.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Api.Scalar.Id


type alias Jsonb =
    Api.Scalar.Jsonb


codecs : Api.Scalar.Codecs Id Jsonb
codecs =
    Api.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecJsonb = defaultCodecs.codecJsonb
        }
