-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Document exposing (TagsOptionalArguments, authorIdentifier, content, docType, id, public, slug, tags, timeStamp, title, user)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import CustomScalarCodecs
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


authorIdentifier : SelectionSet String Api.Object.Document
authorIdentifier =
    Object.selectionForField "String" "authorIdentifier" [] Decode.string


content : SelectionSet String Api.Object.Document
content =
    Object.selectionForField "String" "content" [] Decode.string


docType : SelectionSet String Api.Object.Document
docType =
    Object.selectionForField "String" "docType" [] Decode.string


id : SelectionSet CustomScalarCodecs.Uuid Api.Object.Document
id =
    Object.selectionForField "CustomScalarCodecs.Uuid" "id" [] (CustomScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


public : SelectionSet Bool Api.Object.Document
public =
    Object.selectionForField "Bool" "public" [] Decode.bool


slug : SelectionSet String Api.Object.Document
slug =
    Object.selectionForField "String" "slug" [] Decode.string


type alias TagsOptionalArguments =
    { path : OptionalArgument String }


{-|

  - path - JSON select path

-}
tags : (TagsOptionalArguments -> TagsOptionalArguments) -> SelectionSet CustomScalarCodecs.Jsonb Api.Object.Document
tags fillInOptionals =
    let
        filledInOptionals =
            fillInOptionals { path = Absent }

        optionalArgs =
            [ Argument.optional "path" filledInOptionals.path Encode.string ]
                |> List.filterMap identity
    in
    Object.selectionForField "CustomScalarCodecs.Jsonb" "tags" optionalArgs (CustomScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecJsonb |> .decoder)


timeStamp : SelectionSet CustomScalarCodecs.Timestamptz Api.Object.Document
timeStamp =
    Object.selectionForField "CustomScalarCodecs.Timestamptz" "timeStamp" [] (CustomScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


title : SelectionSet String Api.Object.Document
title =
    Object.selectionForField "String" "title" [] Decode.string


{-| An object relationship
-}
user : SelectionSet decodesTo Api.Object.User -> SelectionSet decodesTo Api.Object.Document
user object_ =
    Object.selectionForCompositeField "user" [] object_ identity
