-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Document exposing (author, children, content, id_, identifier, public, tags, timeCreated, timeUpdated, title, ts_)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


author : SelectionSet Api.ScalarCodecs.Id Api.Object.Document
author =
    Object.selectionForField "ScalarCodecs.Id" "author" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


children : SelectionSet (List String) Api.Object.Document
children =
    Object.selectionForField "(List String)" "children" [] (Decode.string |> Decode.list)


identifier : SelectionSet String Api.Object.Document
identifier =
    Object.selectionForField "String" "identifier" [] Decode.string


timeUpdated : SelectionSet Int Api.Object.Document
timeUpdated =
    Object.selectionForField "Int" "timeUpdated" [] Decode.int


{-| The document's ID.
-}
id_ : SelectionSet Api.ScalarCodecs.Id Api.Object.Document
id_ =
    Object.selectionForField "ScalarCodecs.Id" "_id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


tags : SelectionSet (List String) Api.Object.Document
tags =
    Object.selectionForField "(List String)" "tags" [] (Decode.string |> Decode.list)


timeCreated : SelectionSet Int Api.Object.Document
timeCreated =
    Object.selectionForField "Int" "timeCreated" [] Decode.int


public : SelectionSet Bool Api.Object.Document
public =
    Object.selectionForField "Bool" "public" [] Decode.bool


content : SelectionSet String Api.Object.Document
content =
    Object.selectionForField "String" "content" [] Decode.string


title : SelectionSet String Api.Object.Document
title =
    Object.selectionForField "String" "title" [] Decode.string


{-| The document's timestamp.
-}
ts_ : SelectionSet Api.ScalarCodecs.Long Api.Object.Document
ts_ =
    Object.selectionForField "ScalarCodecs.Long" "_ts" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecLong |> .decoder)
