-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Document_max_fields exposing (authorIdentifier, content, id, identifier, timeCreated, timeUpdated, title)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


authorIdentifier : SelectionSet (Maybe String) Api.Object.Document_max_fields
authorIdentifier =
    Object.selectionForField "(Maybe String)" "authorIdentifier" [] (Decode.string |> Decode.nullable)


content : SelectionSet (Maybe String) Api.Object.Document_max_fields
content =
    Object.selectionForField "(Maybe String)" "content" [] (Decode.string |> Decode.nullable)


id : SelectionSet (Maybe Int) Api.Object.Document_max_fields
id =
    Object.selectionForField "(Maybe Int)" "id" [] (Decode.int |> Decode.nullable)


identifier : SelectionSet (Maybe String) Api.Object.Document_max_fields
identifier =
    Object.selectionForField "(Maybe String)" "identifier" [] (Decode.string |> Decode.nullable)


timeCreated : SelectionSet (Maybe Int) Api.Object.Document_max_fields
timeCreated =
    Object.selectionForField "(Maybe Int)" "timeCreated" [] (Decode.int |> Decode.nullable)


timeUpdated : SelectionSet (Maybe Int) Api.Object.Document_max_fields
timeUpdated =
    Object.selectionForField "(Maybe Int)" "timeUpdated" [] (Decode.int |> Decode.nullable)


title : SelectionSet (Maybe String) Api.Object.Document_max_fields
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)
