-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Document_max_fields exposing (authorIdentifier, content, slug, timeStamp, title)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import CustomScalarCodecs
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


authorIdentifier : SelectionSet (Maybe String) Api.Object.Document_max_fields
authorIdentifier =
    Object.selectionForField "(Maybe String)" "authorIdentifier" [] (Decode.string |> Decode.nullable)


content : SelectionSet (Maybe String) Api.Object.Document_max_fields
content =
    Object.selectionForField "(Maybe String)" "content" [] (Decode.string |> Decode.nullable)


slug : SelectionSet (Maybe String) Api.Object.Document_max_fields
slug =
    Object.selectionForField "(Maybe String)" "slug" [] (Decode.string |> Decode.nullable)


timeStamp : SelectionSet (Maybe CustomScalarCodecs.Timestamptz) Api.Object.Document_max_fields
timeStamp =
    Object.selectionForField "(Maybe CustomScalarCodecs.Timestamptz)" "timeStamp" [] (CustomScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


title : SelectionSet (Maybe String) Api.Object.Document_max_fields
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)
