-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.User exposing (admin, email, firstName, id, lastName, timeEnrolled, timeUpdated, username)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


admin : SelectionSet Bool Api.Object.User
admin =
    Object.selectionForField "Bool" "admin" [] Decode.bool


email : SelectionSet String Api.Object.User
email =
    Object.selectionForField "String" "email" [] Decode.string


firstName : SelectionSet String Api.Object.User
firstName =
    Object.selectionForField "String" "firstName" [] Decode.string


id : SelectionSet Int Api.Object.User
id =
    Object.selectionForField "Int" "id" [] Decode.int


lastName : SelectionSet String Api.Object.User
lastName =
    Object.selectionForField "String" "lastName" [] Decode.string


timeEnrolled : SelectionSet Int Api.Object.User
timeEnrolled =
    Object.selectionForField "Int" "timeEnrolled" [] Decode.int


timeUpdated : SelectionSet Int Api.Object.User
timeUpdated =
    Object.selectionForField "Int" "timeUpdated" [] Decode.int


username : SelectionSet String Api.Object.User
username =
    Object.selectionForField "String" "username" [] Decode.string
