-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.User exposing (admin, email, firstName, id_, lastName, public, timeEnrolled, timeUpdated, ts_)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


admin : SelectionSet Bool Api.Object.User
admin =
    Object.selectionForField "Bool" "admin" [] Decode.bool


email : SelectionSet String Api.Object.User
email =
    Object.selectionForField "String" "email" [] Decode.string


timeUpdated : SelectionSet Int Api.Object.User
timeUpdated =
    Object.selectionForField "Int" "timeUpdated" [] Decode.int


{-| The document's ID.
-}
id_ : SelectionSet Api.ScalarCodecs.Id Api.Object.User
id_ =
    Object.selectionForField "ScalarCodecs.Id" "_id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


public : SelectionSet Bool Api.Object.User
public =
    Object.selectionForField "Bool" "public" [] Decode.bool


timeEnrolled : SelectionSet Int Api.Object.User
timeEnrolled =
    Object.selectionForField "Int" "timeEnrolled" [] Decode.int


lastName : SelectionSet String Api.Object.User
lastName =
    Object.selectionForField "String" "lastName" [] Decode.string


firstName : SelectionSet String Api.Object.User
firstName =
    Object.selectionForField "String" "firstName" [] Decode.string


{-| The document's timestamp.
-}
ts_ : SelectionSet Api.ScalarCodecs.Long Api.Object.User
ts_ =
    Object.selectionForField "ScalarCodecs.Long" "_ts" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecLong |> .decoder)
