-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.Document_constraint exposing (Document_constraint(..), decoder, fromString, list, toString)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "document"

  - Document\_idd\_key - unique or primary key constraint
  - Document\_pkey - unique or primary key constraint

-}
type Document_constraint
    = Document_idd_key
    | Document_pkey


list : List Document_constraint
list =
    [ Document_idd_key, Document_pkey ]


decoder : Decoder Document_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "document_idd_key" ->
                        Decode.succeed Document_idd_key

                    "document_pkey" ->
                        Decode.succeed Document_pkey

                    _ ->
                        Decode.fail ("Invalid Document_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Document_constraint -> String
toString enum =
    case enum of
        Document_idd_key ->
            "document_idd_key"

        Document_pkey ->
            "document_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Document_constraint
fromString enumString =
    case enumString of
        "document_idd_key" ->
            Just Document_idd_key

        "document_pkey" ->
            Just Document_pkey

        _ ->
            Nothing
