-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.Document_update_column exposing (Document_update_column(..), decoder, fromString, list, toString)

import Json.Decode as Decode exposing (Decoder)


{-| update columns of table "document"

  - AuthorIdentifier - column name
  - Content - column name
  - Id - column name
  - Identifier - column name
  - Public - column name
  - Tags - column name
  - TimeCreated - column name
  - TimeUpdated - column name
  - Title - column name

-}
type Document_update_column
    = AuthorIdentifier
    | Content
    | Id
    | Identifier
    | Public
    | Tags
    | TimeCreated
    | TimeUpdated
    | Title


list : List Document_update_column
list =
    [ AuthorIdentifier, Content, Id, Identifier, Public, Tags, TimeCreated, TimeUpdated, Title ]


decoder : Decoder Document_update_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "authorIdentifier" ->
                        Decode.succeed AuthorIdentifier

                    "content" ->
                        Decode.succeed Content

                    "id" ->
                        Decode.succeed Id

                    "identifier" ->
                        Decode.succeed Identifier

                    "public" ->
                        Decode.succeed Public

                    "tags" ->
                        Decode.succeed Tags

                    "timeCreated" ->
                        Decode.succeed TimeCreated

                    "timeUpdated" ->
                        Decode.succeed TimeUpdated

                    "title" ->
                        Decode.succeed Title

                    _ ->
                        Decode.fail ("Invalid Document_update_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Document_update_column -> String
toString enum =
    case enum of
        AuthorIdentifier ->
            "authorIdentifier"

        Content ->
            "content"

        Id ->
            "id"

        Identifier ->
            "identifier"

        Public ->
            "public"

        Tags ->
            "tags"

        TimeCreated ->
            "timeCreated"

        TimeUpdated ->
            "timeUpdated"

        Title ->
            "title"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Document_update_column
fromString enumString =
    case enumString of
        "authorIdentifier" ->
            Just AuthorIdentifier

        "content" ->
            Just Content

        "id" ->
            Just Id

        "identifier" ->
            Just Identifier

        "public" ->
            Just Public

        "tags" ->
            Just Tags

        "timeCreated" ->
            Just TimeCreated

        "timeUpdated" ->
            Just TimeUpdated

        "title" ->
            Just Title

        _ ->
            Nothing
