-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.User_constraint exposing (User_constraint(..), decoder, fromString, list, toString)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "user"

  - Users\_pkey - unique or primary key constraint
  - Users\_username\_key - unique or primary key constraint

-}
type User_constraint
    = Users_pkey
    | Users_username_key


list : List User_constraint
list =
    [ Users_pkey, Users_username_key ]


decoder : Decoder User_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "users_pkey" ->
                        Decode.succeed Users_pkey

                    "users_username_key" ->
                        Decode.succeed Users_username_key

                    _ ->
                        Decode.fail ("Invalid User_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : User_constraint -> String
toString enum =
    case enum of
        Users_pkey ->
            "users_pkey"

        Users_username_key ->
            "users_username_key"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe User_constraint
fromString enumString =
    case enumString of
        "users_pkey" ->
            Just Users_pkey

        "users_username_key" ->
            Just Users_username_key

        _ ->
            Nothing
